name: opentrivia
description: A new Flutter project.
version: 1.0.2+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_custom_clippers: ^1.1.2
  audioplayers: ^0.16.1
  font_awesome_flutter: ^8.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/Images/
    - assets/Categories/
    - assets/